In [2]:
import numpy as np

In [7]:
# Grid
grid = np.matrix([
    [0,0,3,6,0,8,1,0,0],
    [0,4,0,0,0,0,0,7,0],
    [2,0,0,0,0,0,0,0,3],
    [6,0,0,0,9,0,0,0,8],
    [0,0,0,1,0,2,0,0,0],
    [0,0,0,0,6,0,0,0,0],
    [0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0],
    [0,0,0,0,0,0,0,0,0]
])

# grid = np.matrix([
#     [4,0,6,0,0,0,0,3,0],
#     [0,0,0,0,0,0,0,5,1],
#     [0,0,8,0,0,0,0,0,0],
#     [0,0,0,0,0,0,0,0,3],
#     [0,0,4,6,0,9,2,0,0],
#     [5,0,0,0,0,0,0,0,0],
#     [0,0,0,0,0,0,5,0,0],
#     [9,4,0,0,0,0,0,0,0],
#     [0,2,0,0,0,0,3,0,9]
# ])

# Display
print(grid)

[[0 0 3 6 0 8 1 0 0]
 [0 4 0 0 0 0 0 7 0]
 [2 0 0 0 0 0 0 0 3]
 [6 0 0 0 9 0 0 0 8]
 [0 0 0 1 0 2 0 0 0]
 [7 0 0 0 6 0 0 0 4]
 [4 0 0 0 0 0 0 0 1]
 [0 6 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0]]


## Brute Force Algorithm
Implemented from Professor Thorsten Altenkirch in a Computerphile interview [[Link]](https://www.youtube.com/watch?v=G_UYXzGuqvM&t=529s). His algorithm is slightly modified to work under chess sudoku rules.

In [9]:
def Possible(x,y,n):
    global grid
    # Test row
    if n in grid[y]:
        return False

    # Test col
    if n in grid[:,x]:
        return False

    # Test box
    x0,y0 = 3*(x//3),3*(y//3)
    for i in range(3):
        for j in range(3):
            if grid[y0+i,x0+j] == n:
                return False

    # Test knight rule
    for dy in [+1,-1]:                                          # Top, Down
        for dx in [-1,+1]:                                      # Left, Right
            for kind in ([1,2],[2,1]):                          # Kind of jump
                xk,yk = x+kind[0]*dx,y+kind[1]*dy               # Location landed
                if np.logical_and(  xk >= 0 and xk < 9,         # Test jump is not outside the sudoku grid.
                                    yk >= 0 and yk < 9  ): 
                    if grid[yk,xk] == n: return False

    # If all tests passed
    return True

def BruteSolver():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y,x] == 0:
                #if x == 1 and y == 0: print(self.grid)
                for n in np.arange(1,10):
                    if Possible(x, y, n): 
                        grid[y,x] = n
                        BruteSolver()
                        grid[y,x] = 0
                return
    print(grid)


In [10]:
BruteSolver()

[[5 9 3 6 7 8 1 4 2]
 [8 4 6 3 2 1 5 7 9]
 [2 1 7 9 4 5 6 8 3]
 [6 5 1 7 9 4 2 3 8]
 [9 3 4 1 8 2 7 5 6]
 [7 8 2 5 6 3 9 1 4]
 [4 7 5 2 3 6 8 9 1]
 [3 6 9 8 1 7 4 2 5]
 [1 2 8 4 5 9 3 6 7]]
[[5 9 3 6 7 8 1 4 2]
 [8 4 6 3 2 1 5 7 9]
 [2 1 7 9 4 5 6 8 3]
 [6 5 1 7 9 4 2 3 8]
 [9 3 4 1 8 2 7 5 6]
 [7 8 2 5 6 3 9 1 4]
 [4 7 8 2 5 6 3 9 1]
 [3 6 9 8 1 7 4 2 5]
 [1 2 5 4 3 9 8 6 7]]
